server:
  port: 8080

spring:
  #database config
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:
  #h2 console config
  h2:
    console:
      enabled: true
      path: /h2-console
  #jpa sql format prettier
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
